# Image paths used for image recognition
img_paths:
  health:
    full:
      minion: img/health/full_health_minion.png
      boss: img/health/full_health_boss.png
      EB: img/health/full_health_EB.png
    empty:
      minion: img/health/empty_health_minion.png
      boss: img/health/empty_health_boss.png
      EB: img/health/empty_health_EB.png
  buttons:
    exit: img/buttons/exit.png
    close: img/buttons/close.png
    play: img/buttons/play.png
    architect: img/buttons/architect.png
    reward: img/buttons/reward.png
  dialogs:
    turn_in_mission: img/dialogs/turn_in_mission.png
    get_mission_details: img/dialog/get_mission_details.png
    accept_mission: img/dialog/accept_mission.png
    rating_popup: img/dialogs/rating_popup.png
  nav_box: img/nav_box.png
# Number of times the mission is cleared before stopping
number_of_runs: 5
# Name of contact for targeting purposes
name_of_contact: Steve
# Generic positions for the mouse to click
screen_positions:
  top:
    left: 0,0
    middle: 0,0
    right: 0,0
  center:
    left: 0,0
    middle: 0,0
    right: 0,0
  bottom:
    left: 0,0
    middle: 0,0
    right: 0,0
